#pragma once

#include <Arduino.h>

static const char HTML_PAGE[] PROGMEM =
  "<!doctype html><html><head><meta charset='utf-8'/>"
  "<meta name='viewport' content='width=device-width,initial-scale=1'/>"
  "<title>Bike Local</title>"
  "<style>"
  ":root{--bg:#0b1220;--card:#0f172a;--line:rgba(255,255,255,.10);--muted:#94a3b8;--txt:#e5e7eb;"
  "--ok:#22c55e;--bad:#ef4444;--warn:#f97316}"
  "*{box-sizing:border-box}"
  "body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;margin:0;"
  "background:radial-gradient(900px 480px at 10% 10%,rgba(34,197,94,.14),transparent 60%),"
  "radial-gradient(900px 480px at 90% 0%,rgba(249,115,22,.14),transparent 55%),var(--bg);"
  "color:var(--txt)}"
  ".wrap{max-width:860px;margin:0 auto;padding:18px}"
  ".top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;"
  "margin-bottom:10px;flex-wrap:wrap}"
  ".title{font-size:16px;font-weight:900;letter-spacing:.2px}"
  ".grid{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}"
  "@media(max-width:860px){.grid{grid-template-columns:1fr}}"
  ".card{background:linear-gradient(180deg,rgba(255,255,255,.04),rgba(255,255,255,.02));"
  "border:1px solid var(--line);border-radius:16px;padding:14px;"
  "box-shadow:0 10px 30px rgba(0,0,0,.25)}"
  ".kv{display:grid;grid-template-columns:140px 1fr;gap:8px;font-size:13px}"
  ".k{color:var(--muted)}.v{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
  ".chips{display:flex;flex-wrap:wrap;gap:8px}"
  ".chip{display:inline-flex;align-items:center;gap:8px;padding:6px 10px;border-radius:999px;"
  "border:1px solid var(--line);background:rgba(255,255,255,.03);font-size:12px}"
  ".dot{width:8px;height:8px;border-radius:50%}"
  ".dot.ok{background:var(--ok)}.dot.bad{background:var(--bad)}.dot.warn{background:var(--warn)}"
  "label{display:block;font-size:12px;color:var(--muted);margin-bottom:6px}"
  "input{width:100%;padding:12px;border-radius:12px;border:1px solid var(--line);"
  "background:rgba(0,0,0,.22);color:var(--txt);outline:none}"
  "input:focus{border-color:rgba(34,197,94,.55);box-shadow:0 0 0 3px rgba(34,197,94,.16)}"
  ".row{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}"
  "button{flex:1;min-width:140px;padding:12px 14px;border-radius:14px;"
  "border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);"
  "color:var(--txt);font-weight:900;cursor:pointer;transition:transform .06s,filter .12s,opacity .12s}"
  "button:active{transform:translateY(1px)}"
  "button.primary{background:rgba(34,197,94,.18);border-color:rgba(34,197,94,.35)}"
  "button.danger{background:rgba(239,68,68,.18);border-color:rgba(239,68,68,.35)}"
  "button.warn{background:rgba(249,115,22,.18);border-color:rgba(249,115,22,.35)}"
  "button.gray{background:rgba(51,65,85,.22);border-color:rgba(51,65,85,.35)}"
  "button:hover{filter:brightness(1.06)}"
  "button[disabled]{opacity:.45;cursor:not-allowed;filter:none;transform:none}"
  ".msg{margin-top:10px;color:var(--muted);font-size:12px;min-height:18px}"
  ".banner{display:none;margin-top:10px;padding:10px 12px;border-radius:14px;"
  "border:1px solid rgba(239,68,68,.35);background:rgba(239,68,68,.12);font-size:12px}"
  ".banner.show{display:block}"
  ".muteWrap{display:none;margin-top:10px}.muteWrap.show{display:block}"
  "</style></head><body><div class='wrap'>"
  "<div class='top'>"
  "<div class='title'>&#x1F6B2; Bike Local Control</div>"
  "<div class='chips'>"
  "<span class='chip' id='chipWifi'><span class='dot bad'></span><span>Wi-Fi</span><b id='wifiTxt'>OFF</b></span>"
  "<span class='chip' id='chipNet'><span class='dot bad'></span><span>Internet</span><b id='netTxt'>BAD</b></span>"
  "<span class='chip' id='chipVib'><span class='dot bad'></span><span>Vibe</span><b id='vibTxt'>OFF</b></span>"
  "</div>"
  "</div>"
  "<div class='grid'>"
  "<div class='card'>"
  "<div class='kv'>"
  "<div class='k'>State</div><div class='v' id='st'>-</div>"
  "<div class='k'>Locked</div><div class='v' id='locked'>-</div>"
  "<div class='k'>Armed</div><div class='v' id='armed'>-</div>"
  "<div class='k'>Alarm</div><div class='v' id='alarm'>-</div>"
  "<div class='k'>GPS</div><div class='v' id='gps'>-</div>"
  "<div class='k'>Speed</div><div class='v' id='spd'>-</div>"
  "<div class='k'>IMU</div><div class='v' id='imu'>-</div>"
  "<div class='k'>Buffer</div><div class='v' id='buf'>-</div>"
  "</div>"
  "<div class='banner' id='alarmBanner'>Alarm active. Use <b>UNLOCK</b> to stop.</div>"
  "<div class='muteWrap' id='muteWrap'>"
  "<div class='row'>"
  "<button class='gray' id='btnMuteVibe' type='button'>STOP VIBRATION</button>"
  "</div>"
  "</div>"
  "</div>"
  "<div class='card'>"
  "<label>4-digit PIN</label>"
  "<input id='pin' inputmode='numeric' maxlength='4' placeholder='****'/>"
  "<div class='row'>"
  "<button id='btnLock' class='danger' onclick=\"sendCmd('lock')\">LOCK</button>"
  "<button id='btnUnlock' class='primary' onclick=\"sendCmd('unlock')\">UNLOCK</button>"
  "<button id='btnArm' class='warn' onclick=\"sendCmd('arm')\">ARM</button>"
  "<button id='btnBuzz' class='gray' onclick=\"sendCmd('buzz')\">BUZZ</button>"
  "</div>"
  "<div class='msg' id='msg'></div>"
  "</div>"
  "</div>"
  "<script>"
  "function setChip(id,mode){const e=document.getElementById(id);const d=e.querySelector('.dot');"
  "d.className='dot '+(mode==='ok'?'ok':mode==='warn'?'warn':'bad');}"
  "let alarmOn=false,vibMuted=false,vibOk=false,vibTimer=0,vibFailAt=0;"
  "function vibUI(){const t=document.getElementById('vibTxt');"
  "if(!navigator.vibrate){t.textContent='N/A';setChip('chipVib','bad');return;}"
  "if(!alarmOn){t.textContent='OFF';setChip('chipVib','bad');return;}"
  "if(vibMuted){t.textContent='MUTED';setChip('chipVib','warn');return;}"
  "t.textContent=vibOk?'ON':'AUTO';setChip('chipVib',vibOk?'ok':'warn');}"
  "function vibKick(){vibOk=!!navigator.vibrate(300);"
  "if(!vibOk){if(!vibFailAt)vibFailAt=Date.now();}else{vibFailAt=0;"
  "const m=document.getElementById('msg');"
  "if(m.textContent==='Tap screen to allow vibration.')m.textContent='';}"
  "vibUI();vibTimer=setTimeout(vibKick,450);"
  "if(alarmOn&&!vibMuted&&vibFailAt&&(Date.now()-vibFailAt>1500)){"
  "const m=document.getElementById('msg');"
  "if(!m.textContent)m.textContent='Tap screen to allow vibration.';}}"
  "function startVibeLoop(){if(!alarmOn||vibMuted||vibTimer||!navigator.vibrate)"
  "{vibOk=false;vibUI();return;}navigator.vibrate(60);vibKick();}"
  "function stopVibeLoop(){if(vibTimer){clearTimeout(vibTimer);vibTimer=0;}"
  "if(navigator.vibrate)navigator.vibrate(0);vibOk=false;vibFailAt=0;vibUI();}"
  "document.getElementById('btnMuteVibe').addEventListener('click',()=>{"
  "vibMuted=true;stopVibeLoop();"
  "document.getElementById('msg').textContent='Vibration muted.';"
  "document.getElementById('btnMuteVibe').disabled=true;vibUI();});"
  "window.addEventListener('pointerdown',()=>{"
  "if(alarmOn&&!vibMuted&&!vibTimer)startVibeLoop();},{passive:true});"
  "async function refresh(){try{"
  "const r=await fetch('/status',{cache:'no-store'});"
  "const j=await r.json();"
  "document.getElementById('wifiTxt').textContent=j.wifi?'ON':'OFF';"
  "document.getElementById('netTxt').textContent=j.net?'OK':'BAD';"
  "setChip('chipWifi',j.wifi?'ok':'bad');setChip('chipNet',j.net?'ok':'bad');"
  "document.getElementById('st').textContent=j.state||'-';"
  "document.getElementById('locked').innerHTML=j.locked?"
  "'<b style=color:var(--bad)>YES</b>':'<b style=color:var(--ok)>NO</b>';"
  "document.getElementById('armed').innerHTML=j.armed?"
  "'<b style=color:var(--warn)>YES</b>':'<b style=color:var(--ok)>NO</b>';"
  "document.getElementById('alarm').innerHTML=j.alarm?"
  "'<b style=color:var(--bad)>YES</b>':'<b style=color:var(--ok)>NO</b>';"
  "document.getElementById('gps').textContent=j.gps||'-';"
  "document.getElementById('spd').textContent=j.speed||'-';"
  "document.getElementById('imu').textContent=j.imu||'-';"
  "document.getElementById('buf').textContent=j.buf||'-';"
  "const lk=!!j.locked,ar=!!j.armed,al=!!j.alarm;"
  "document.getElementById('btnLock').style.display=(!lk&&!al)?'':'none';"
  "document.getElementById('btnUnlock').style.display=(lk||al)?'':'none';"
  "document.getElementById('btnArm').style.display=lk?'':'none';"
  "document.getElementById('btnArm').disabled=ar;"
  "document.getElementById('btnArm').textContent=ar?'ARMED':'ARM';"
  "if(al){alarmOn=true;"
  "document.getElementById('alarmBanner').className='banner show';"
  "document.getElementById('muteWrap').className='muteWrap show';"
  "document.getElementById('btnMuteVibe').disabled=vibMuted;"
  "if(!vibMuted)startVibeLoop();"
  "}else{alarmOn=false;vibMuted=false;stopVibeLoop();"
  "document.getElementById('alarmBanner').className='banner';"
  "document.getElementById('muteWrap').className='muteWrap';}"
  "vibUI();}catch(e){}}"
  "async function sendCmd(c){const p=document.getElementById('pin').value||'';"
  "document.getElementById('msg').textContent='Sending...';"
  "try{const r=await fetch('/api/'+c+'?pin='+encodeURIComponent(p),{method:'POST'});"
  "const t=await r.text();document.getElementById('msg').textContent=t;refresh();"
  "}catch(e){document.getElementById('msg').textContent='ERR';}}"
  "vibUI();setInterval(refresh,1200);refresh();"
  "</script></div></body></html>";
